package com.example.to_doapplication.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.tasks.await

class AuthManager(private val context: Context) {
    private val auth = FirebaseAuth.getInstance()
    private val credentialManager = CredentialManager.create(context)

    suspend fun registerWithEmail(email: String, password: String): String? {
        return try {
            auth.createUserWithEmailAndPassword(email, password).await()
            null
        } catch (e: Exception) {
            e.localizedMessage ?: e.message ?: "Registration failed"
        }
    }

    suspend fun loginWithEmail(email: String, password: String): String? {
        return try {
            auth.signInWithEmailAndPassword(email, password).await()
            null
        } catch (e: Exception) {
            e.localizedMessage ?: e.message ?: "Login failed"
        }
    }

    @Suppress("BooleanLiteralArgument", "DiscouragedApi")
    suspend fun signInWithGoogle(): Boolean {
        try {
            // Note: R.string.default_web_client_id is automatically generated by the
            // google-services plugin when google-services.json is present.
            // If it's missing, ensure the JSON file is in the app/ directory.
            val webClientId = context.getString(
                context.resources.getIdentifier("default_web_client_id", "string", context.packageName),
            )

            if (webClientId.isEmpty()) {
                throw IllegalStateException("Web Client ID is missing. Check google-services.json")
            }

            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(webClientId)
                .setAutoSelectEnabled(true)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val result = credentialManager.getCredential(context, request)
            val credential = result.credential

            if ((credential is CustomCredential) && (credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL)) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val firebaseCredential = GoogleAuthProvider.getCredential(googleIdTokenCredential.idToken, null)
                auth.signInWithCredential(firebaseCredential).await()
                return true
            }
            return false
        } catch (e: Exception) {
            e.printStackTrace()
            return false
        }
    }

    fun signOut() {
        auth.signOut()
    }

    fun getCurrentUserId(): String? {
        return auth.currentUser?.uid
    }

    fun getCurrentUserDisplayName(): String? {
        return auth.currentUser?.displayName ?: auth.currentUser?.email
    }
}
